services:
  postgres:
    image: postgres:16
    container_name: pg-docker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: midterm-app
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_UPLOAD_DIR: /data/uploads/products
      APP_UPLOAD_BASE_URL: /uploads/products
    ports:
      - "8080:8080"
    volumes:
      - ./uploads/products:/data/uploads/products
    networks:
      - app-network

volumes:
  pgdata:
  uploads-data:
networks:
  app-network:
    driver: bridge