spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/midterm_db}
    username: ${SPRING_DATASOURCE_USERNAME:midterm_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:midterm_pass123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect